### ISSUE TITLE
[Feature Request] Piggyback Channel Filter

### ISSUE THREAD

**Issue by qoomon** [aws-samples/shopfloor-connectivity#6]
For my current customer setup I need to read multiple parameters from an S7 PLC in high frequency (10ms)

The parameters change infrequently so i make use of a change filter (`{"Type": "Always", "AtLeast": 60_000}`).
One parameter is `system time` however this change rapidly by its nature, however I only need this parameter if any other parameter has changed.

Is the any way to achieve this behaviour?

**Comment by arieleeuw** [comment]
Would it work for you to include timestamps at value level by setting  the "TimestampLevel" configuration to "Channel" or "Both"?

**Comment by arieleeuw** [comment]
So basically you need an filter a value, in case the system date-time, if after applying the filters, one or more other values are included in the output set of values.

**Comment by qoomon** [comment]
Yes, i need a `piggyback` filter. e.g. 
```json
{ 
    "Type": "Piggyback", 
    "Channels": [ "OtherChannelA", "OtherChannelB" ],
}
```
if `"Channels"` is not set or empty, it should be send, if any other channel of the corresponding schedule is send.

**Comment by arieleeuw** [comment]
Implemented in version 1.1.1  by adding Condition filtering.

https://github.com/aws-samples/shopfloor-connectivity/tree/mainline/docs#condition-filters

Add the new Condition filters section at top level of config

```json
  "ConditionFilters":{
      "NotJustTheTimeStamp": {
             "Operator" : "only",
             "Value" : "false"
            }
      }
  }
  

```

  Add 
  ```json
     "ConditionFilter" : "NotJustTheTimeStamp"
```

 to the timestamp channel for your sources

**Comment by qoomon** [comment]
Thanks a lot

**Comment by qoomon** [comment]
What would be the easiest solution for ConditionFilters to send Channel A and B Values only if any other channel has a value?
Or would it work if I apply NotJustTheTimeStamp on channel A and B?

**Comment by arieleeuw** [comment]
There is a set of new operators you can use to build condition filters 
https://github.com/aws-samples/shopfloor-connectivity/tree/mainline/docs#condition-filters

The easiest one is to define a condition using the "**present**" operator which checks if that other channel has a value and apply that on channel A and B. So if you want to output channel A and channel B only if channel C exists then define this condition:

```json
"ConditionFilters":{
    "OnlyIfCExists": 
          {
           "Operator" : "present",
           "Value" : "C"
          }
    }
```

And then on channel A and B use the "OnlyIfCExists" as the value for "ConditionFilter".

```json
"Channels" : {
  "A": {
          "NodeId": "ns=0;i=2256",
          "ConditionFilter" : "OnlyIfCExists"
      },
 "B": {
          "NodeId": "ns=0;i=2259",
          "ConditionFilter" : "OnlyIfCExists"
      }
}
```

There are also operator to check if a field is **absent**, if **any**, **none** or **all** fields in a list are there and you can combine multiple operators using the **and** and **or** operator. I've include some examples in the documentation.

_p.s. instead of "NotJustTheTimeStamp" in my previous message or the name I've used in this one, you can give a condition filter any name which describes its purpose the best in your situation. The name just identifies a filter, which is one, or a combination of condition filter operators and is used to apply that filter on one or more channels by setting the value of "ConditionFilter" to that name._

**Comment by arieleeuw** [comment]
The easiest way is to use the "**present**" operator in a condition filter. The condition filter named "OnlyIfCExists" (use any name you want) will check if channel C has a value in it's source.

```json
  "CondtionFilters" : {
      "OnlyIfCExists" : {
          "Operator" : "present",
           "Value" : "C"
      }
  }
```

 Then apply this filter to channel A and B. A and B are only in the output if C has a value.
 
```json
 "Channels" : {
  "A": {
          "NodeId": "ns=0;i=2256",
          "ConditionFilter" : "OnlyIfCExists"
      },
 "B": {
          "NodeId": "ns=0;i=2259",
          "ConditionFilter" : "OnlyIfCExists"
      }
  "C": {
          "NodeId": "ns=0;i=2260"
      }
}
```
 
If you also have a ChangeFilter or a ValueFilter on a channels, these are applied first on all these channels before the condition filter is applied. So if C has a value, but is filtered out using a Value or a ChangeFilter, the because of the ConditonFilter A and B will filtered out as well.

There is a rich set op operators which let you test if channels are **present** or **absent**, or if **any**, **none** or **all** channels in a list of channels are present. It is even possible to combine multiple operators using the **or** and **and** operators. See complete list of operators and examples at https://github.com/aws-samples/shopfloor-connectivity/tree/mainline/docs#condition-filters
